### ISSUE TITLE
slideInDownBig wrong prefix

### ISSUE THREAD

**Issue by jmarsh376** [geoffgraham/animate.scss#17]
Hi Geoff,

First off thank you for this excellent library. It has saved me a load of time!

I am just letting you know that In the file _fadeInDownBig.scss

you have set the transform prefix to -webkit-transform instead of just transform like the other animations use. 

removing the -webkit- prefix fixes the issue on none webkit browsers of coarse:)

Thanks again!

Jack

**Comment by geoffgraham** [comment]
Thanks man! Done hand handled. :)
