### ISSUE TITLE
How to handle vendor prefixes?

### ISSUE THREAD

**Issue by geoffgraham** [geoffgraham/animate.scss#22]
I've gone back and forth on how to handle vendor prefixes here. In the past week, I've made a commit that removed them entirely, then went back and merged a [pull request](https://github.com/geoffgraham/animate.scss/pull/20) that elegantly put them back in with mixins.

The question is (1) whether we're all cool with mixins as a means for handling vendor prefixes or (2) whether there is another preferred method?

I'm asking the question out in the open because the intent of this is to keep things as unobtrusive as possible. By that, I mean anyone should be able to drop this into their project and have it work. To illustrate that point, I personally prefer using Grunt/Autoprefixer to handle prefixing but know that would require making choices that have an impact on other people's projects and I'd hate for that to happen.

Either way, I'll put it out there. Just want some healthy dialogue and nothing else. :)

Cheers!
Geoff

**Comment by mbme** [comment]
I think that mixin is probably the best (and idiomatic) way to handle vendor prefixes.

In any case you can add some global config option for mixin to generate only non-prefixed properties and then process generated css with Autoprefixer.

And thanks for work :)

**Comment by wmadden** [comment]
I think the best approach is to leave this to the consumer of the library, using Autoprefixer for example. Otherwise you have to make assumptions about the environment that `animate.scss` is used in.

**Comment by sarukuku** [comment]
I agree with @wmadden. Prefixing is a task best left for the build process.

**Comment by felics** [comment]
:+1: +1 @wmadden.

**Comment by geoffgraham** [comment]
Nice, thanks for the feedback everyone! I think this provides some good ammo for future updates.
