### ISSUE TITLE
Missing animations

### ISSUE THREAD

**Issue by obsidianart** [geoffgraham/animate.scss#25]
It seems the bower repository is missing some animation.
Animate.scss contains zoom and other animations which are not on the bower installed version.

**Comment by geoffgraham** [comment]
That's strange! Seems to include everything when I import the repo in via Bower. Have you tried running `bower update` on it to make sure it's pulling the latest?

**Comment by xthilakx** [comment]
This issue should be closed because Zoom is available. Jello is missing, but I already see it as a todo. Will send a pull request for jello soon.

**Comment by obsidianart** [comment]
That's my animate.scss, bower version animate.css-scss#~3.1.0 . As you can see various animation are not in this file. Am I using the wrong version or bower have an older version?

// Import the animations
@import 
  "_attention/attention.scss",
  "_bouncing-entrances/bouncing-entrances.scss",
  "_bouncing-exits/bouncing-exits.scss",
  "_fading-entrances/fading-entrances.scss",
  "_fading-exits/fading-exits.scss",
  "_flippers/flippers.scss",
  "_lightspeed/lightspeed.scss",
  "_rotating-entrances/rotating-entrances.scss",
  "_rotating-exits/rotating-exits.scss",
  "_specials/specials.scss";

**Comment by xthilakx** [comment]
@obsidianart: Yes.. you are using an older version. This is what I see: 

// Import the animations
@import
  "_attention-seekers/attention-seekers.scss",
  "_bouncing-entrances/bouncing-entrances.scss",
  "_bouncing-exits/bouncing-exits.scss",
  "_fading-entrances/fading-entrances.scss",
  "_fading-exits/fading-exits.scss",
  "_flippers/flippers.scss",
  "_lightspeed/lightspeed.scss",
  "_rotating-entrances/rotating-entrances.scss",
  "_rotating-exits/rotating-exits.scss",
  "_sliding-entrances/sliding-entrances.scss",
  "_sliding-exits/sliding-exits.scss",
  "_specials/specials.scss",
  "_zooming-entrances/zooming-entrances.scss",
  "_zooming-exits/zooming-exits.scss";

**Comment by obsidianart** [comment]
That's the output of bower info animate.css-scss

bower animate.css-scss#*        cached git://github.com/Igosuki/animate.scss.git#3.1.0
bower animate.css-scss#*      validate 3.1.0 against git://github.com/Igosuki/animate.scss.git#*

{
  name: 'animate.css-scss',
  version: '3.1.0',
  homepage: 'https://github.com/geoffgraham/animate.scss',
  authors: [
    'geoffgraham <geoff@geoffgraham.me>'
  ],
  description: 'An up to date port of Dan Eden\'s Animate.css to SASS',
  main: [
    'animate.scss'
  ],
  keywords: [
    'animate.scss',
    'animate.css',
    'animate'
  ],
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ]
}

Available versions:
  - 3.1.0

**Comment by geoffgraham** [comment]
I'm going to go ahead and close this one out since I haven't been able to replicate and haven't seen any other reports. Let's keep an eye on it though!

**Comment by obsidianart** [comment]
I explained my problem and try to uninstall and install again. I see the same result with the same missing animations. have you tried to replicate and it does work for you? Are you using the public repository or a private one?

**Comment by geoffgraham** [comment]
I'm using the public one and was not able to replicate. Sorry man! Perhaps someone else will chime in here with the same issue and we can see where there might be patterns.

**Comment by GabiGrin** [comment]
Same issue here. Bower installed regularly, and I get 3.1.0
I see you have no tags in the repo, that might be the issue. Try tagging the latest commit with version 3.2.0.

**Comment by geoffgraham** [comment]
Sure thing, done!
https://github.com/geoffgraham/animate.scss/releases/tag/3.2.0

**Comment by GabiGrin** [comment]
Haha I was just about to comment that I probably missed it because I see it now, you we're quick :)
Still doesn't get it though.. argh..
![image](https://cloud.githubusercontent.com/assets/3727015/9588882/79259ea8-5033-11e5-9ebe-f4fe901f81ed.png)

Here is another attempt even after clearing bower cache
![image](https://cloud.githubusercontent.com/assets/3727015/9588914/a9a9b7c6-5033-11e5-8b1b-139162b6d4c9.png)

Now I see the issue! 
The bower repo that is connected to "animate.css-scss" is not yours, but this dudes -> https://github.com/Igosuki/animate.scss
See here -> 
![image](https://cloud.githubusercontent.com/assets/3727015/9588945/f80c67ec-5033-11e5-8d50-1c34e61c4794.png)

**Comment by GabiGrin** [comment]
I ended up implicitly installing yours by adding this to my bower.json:
"animate.css-scss": "https://github.com/geoffgraham/animate.scss.git#latest"

**Comment by geoffgraham** [comment]
Ha! That's great to know. Guess I shoulda caught that earlier. That's the darn thing about repos with similar titles. :)

Thanks for checking!

**Comment by GabiGrin** [comment]
Glad to help, thanks for the great job yourself :)
Hope you'll get around it!
