### ISSUE TITLE
$count parameter doesn't seem to be in the _properties file

### ISSUE THREAD

**Issue by davebowker** [geoffgraham/animate.scss#30]
Also, some animations it says does not $count. The example on the readme doesn't work due to this.

```
.your-class-name {
  @include bounceIn(
    $duration: 1s,
    $count: 2,
    $delay: .2s,
    $function: ease, 
    $fill: both
  );
}
```

**Comment by geoffgraham** [comment]
Hmm, that's strange. The demo animation seems to work for me and I also see that `$count` is called in the [`_bounceIn.scss`](https://github.com/geoffgraham/animate.scss/blob/master/_bouncing-entrances/_bounceIn.scss).

Is there perhaps something else at play that I might be missing?

**Comment by davebowker** [comment]
Right, think I found the issue.

Your github is up-to-date, obviously, but I installed via bower. 

```
C:\xampp\htdocs\newwws.io.bs4 [master]> bower install animate.css-scss#latest
bower cached        git://github.com/Igosuki/animate.scss.git#3.1.0
bower validate      3.1.0 against git://github.com/Igosuki/animate.scss.git#*
```

IGOSUKI... Is 36 commits behind your master.

D
