### ISSUE TITLE
Call animations by a class name

### ISSUE THREAD

**Issue by davebowker** [geoffgraham/animate.scss#31]
Is there a way to call animations by using classes on the HTML, as animate.css works now.

EG, another file which links everything up.

```
.bounce {
  @include bounce();
}
.flash {
  @include flash();
}
.pulse {
  @include pulse();
}
```

So in the HTML I can have:
```
<div class="animate bounce">
Some Content
</div>
```

Obviously this method would just use the defaults as there would be no way to change animation parameters in the HTML.

**Comment by geoffgraham** [comment]
Good question but, no, there is not a way to call an animation by class name. That was intentional though since you could really just rely on Animate.css for that ability whereas Animate.scss helps use semantic class names and keep the CSS file size down.

Hope this helps!

**Comment by davebowker** [comment]
Fair enough. :)
