### ISSUE TITLE
Update Bower

### ISSUE THREAD

**Issue by mateeyow** [geoffgraham/animate.scss#35]
Bower install only saves version 3.1.0 and some animations are missing like slide sliding exit

**Comment by geoffgraham** [comment]
Hey there! Looks like `bower.json` is set to the latest release: https://github.com/geoffgraham/animate.scss/commit/9ac26a31790ceac10632a2114853e62497508673

**Comment by mateeyow** [comment]
Oh. So the name changed? You should consider updating the `README` file. :)
