### ISSUE TITLE
#30

### ISSUE THREAD

**Issue by davebowker** [geoffgraham/animate.scss#38]
Flagging this up again as I think I found out whey $count wasn't working 

#30

**Comment by geoffgraham** [comment]
Thanks dude! Updated the README with the appropriate repo here: https://github.com/geoffgraham/animate.scss/commit/f04891e370a58dbc30491039fd76640d8e5503f6

**Comment by davebowker** [comment]
No worries. I knew something wasn't right. :)

On 20 October 2015 at 19:52, Geoff Graham <notifications@github.com> wrote:

> Thanks dude! Updated the README with the appropriate repo here: f04891e
> <https://github.com/geoffgraham/animate.scss/commit/f04891e370a58dbc30491039fd76640d8e5503f6>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffgraham/animate.scss/issues/38#issuecomment-149665911>
> .
>



-- 

*Dave Bowker*
*Website:*  http://davebowker.com* | Twitter:* @davebowker
<http://twitter.com/davebowker> | *Mobile:* 07879630598 | *LinkedIn:*
http://uk.linkedin.com/in/davebowker


<http://www.ultraknowledge.com/?ref=email>
