### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by jamiehutber** [geoffgraham/animate.scss#39]
Hey, I'm sure there is a reason, but thought I'd just ask and see if you had any plans to add this to the npm packages?

**Comment by geoffgraham** [comment]
Good question! I have not considered that at all. What are your thoughts?

**Comment by mchlbrnd** [comment]
Hi @geoffgraham,

I've published it to npmjs under https://www.npmjs.com/package/animatewithsass. What is your npmjs username so I can add you to the list of collaborators. :)

Cheers!

**Comment by geoffgraham** [comment]
Sorry dude, been falling behind lately. 

My username is: geoffgraham

I'll roll this stuff in momentarily. :)
