### ISSUE TITLE
A few more customizations

### ISSUE THREAD

**Issue by AlexSwensen** [geoffgraham/animate.scss#44]
I realize this is a large request, but i find at times i wan't to apply custom transform values on a case-by-case basis. 2000px offsets makes things very cumbersome, and at other times a 100% value just doesn't work with some components. I would love to be able to pass in a custom distance, while still using the animation name... not sure if thats possible.

**Comment by geoffgraham** [comment]
That's an interesting question!

I think making a fork of this repo and replacing the 100% values with your custom one would be the most efficient way to go in this case. Or perhaps, create a variable within the mixins that allows you to establish the offset on a case-by-case basis.
