### ISSUE TITLE
How to use with JQuery 

### ISSUE THREAD

**Issue by danmv** [geoffgraham/animate.scss#45]
Hi there, 

I have been using the Animate.css for a while now. I decided to give a try to this library Animate.scss but after compiling and trying to do this: 
$('#triggerElement').on('click', function () {
      $('#my-element').addClass('animated bounce'); 
});

it doesn't work. is there a reason why? do I really have to go and create another class and include a animation mixin to be able to animate an element via JQuery?

**Comment by geoffgraham** [comment]
Hey @danmv!

I think the reason is that this library doesn't include an `animated` class like the original Animate.css library: https://github.com/daneden/animate.css/blob/master/source/_base.css

It might be worth considering adding that file to here as well. Thanks for the heads up!
