### ISSUE TITLE
Seems to be compiling huge css files

### ISSUE THREAD

**Issue by vjasterix** [geoffgraham/animate.scss#46]
I figured it should probably just import dynamically, so that only @included options are compiled into the final .css file via sass --watch. However it seems to import all classes by default. Am I doing something wrong? I am importing the default animate.scss at the rootpath as documented. Adds 400kb to my build! But the final @import in your chain is importing the partials so I'm a bit confused.

**Comment by geoffgraham** [comment]
That's odd! The full un-minified CSS file with all animations is around 228KB, so 400KB sounds very large indeed. Tried to compile with only a few imports and all seems to be working ok. There could be something I'm missing as well, but it might be worth checking your import statements to make sure only what you need is importing.
